"""Edit booking

Revision ID: 0c7d739a10f9
Revises: d4276fb32098
Create Date: 2024-05-27 23:09:09.052608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c7d739a10f9'
down_revision: Union[str, None] = 'd4276fb32098'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_to', sa.DateTime(), nullable=False))
        batch_op.alter_column('booking_from',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('workplace_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('workplace_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('booking_from',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_column('booking_to')

    # ### end Alembic commands ###
